name: my_dating
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.15.1


  cupertino_icons: ^1.0.2
  firebase_database: ^10.2.5
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  intl: ^0.18.0
  get: ^4.6.5
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
